name: CI

on: [push]

jobs:
  ci-on-ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-macos-12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-windows-2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc thue.cc
        shell: cmd

  ci-on-windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc thue.cc
        shell: cmd
