name: CI

on: [push, pull_request]

jobs:
  ci-via-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build

  ci-on-ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-macos-12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Test
        run: make check

  ci-on-windows-2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc thue.cc
        shell: cmd
      - uses: actions/upload-artifact@v3
        with:
          name: windows-2022-thue-exe
          path: thue.exe

  ci-on-windows-2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc thue.cc
        shell: cmd
      - uses: actions/upload-artifact@v3
        with:
          name: windows-2019-thue-exe
          path: thue.exe
