name: CI

on: [push, pull_request]

jobs:
  ci-via-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix build

  ci-on-ubuntu-24_04:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
        working-directory: ./src
      - name: Test
        run: make check
        working-directory: ./src

  ci-on-ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
        working-directory: ./src
      - name: Test
        run: make check
        working-directory: ./src

  ci-on-macos-15:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
        working-directory: ./src
      - name: Test
        run: make check
        working-directory: ./src

  ci-on-macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
        working-directory: ./src
      - name: Test
        run: make check
        working-directory: ./src

  ci-on-macos-13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
        working-directory: ./src
      - name: Test
        run: make check
        working-directory: ./src

  ci-on-windows-2025:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc thue.cc
        shell: cmd
        working-directory: ./src
      - uses: actions/upload-artifact@v4
        with:
          name: windows-2025-thue-exe
          path: src/thue.exe

  ci-on-windows-2022:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc thue.cc
        shell: cmd
        working-directory: ./src
      - uses: actions/upload-artifact@v4
        with:
          name: windows-2022-thue-exe
          path: src/thue.exe

